name: next Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - next

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies & Build
        run: |
          npm ci
          npm run bootstrap
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Release to @next tag
        run: |
          npm run changeset pre enter next
          npm run changeset version
          git add .
          git commit -m "ci(changesets): version packages"
          npm run changeset publish
          git push --set-upstream origin changeset-release/next --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.PANKOD_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
